vscode:
  extensions:
    - xabikos.JavaScriptSnippets@1.7.2:XXmiw8r7K3Guifex/E73aQ==
    - lihui.vs-color-picker@1.0.0:hzx9jPABxr2kCAYpdSUNcA==
    - dsznajder.es7-react-js-snippets@2.5.0:gafKiz73ol+9oCiMLaS6hw==
    - syler.sass-indented@1.7.3:objRBaERjCLIw1OKOvEjew==